Login
debo-centbit/auth-ui pull request #4
Opened 2023-08-22 17:12 UTC by blossomese

Merging initial changes

2023-08-22 17:19 UTC, blossomese reviewed
I have reviewed these files, and they are good to go.

2023-08-23 16:36 UTC, ayuba-dn commented on src/App.css
> -  background-color: #282c34;
I will suggest you use css variables for color codes. To enable dynamic theming

2023-08-23 16:37 UTC, ayuba-dn commented on src/App.css
> -  color: #61dafb;
use css variable here too

2023-08-23 16:46 UTC, ayuba-dn requested changes
Generally a nice work, kindly address the few comments

2023-08-29 09:51 UTC, closed without merging